#!/usr/bin/env bash

if [ -z "$1" ]; then
    echo "Missing argument (commit message). Did you try to run this manually?"
    exit 1
fi

commitTitle="$(cat $1 | head -n1)"

# ignore merge requests
if echo "$commitTitle" | grep -qE "^Merge branch \'"; then
    echo "Commit hook: ignoring branch merge"
    exit 0
fi

# check semantic versioning scheme
if ! echo "$commitTitle" | grep -qE '^(?:feat|fix|docs|style|refactor|perf|test|chore): \w+$'; then
    echo "Your commit title did not follow semantic versioning: '$commitTitle'"
    echo "Please see https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716"
    exit 1
fi
