export const ADD_GAME = 'ADD_GAME';
export const DELETE_GAME = 'DELETE_GAME';
export const FETCH_ERROR = 'FETCH_ERROR';
export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const REORDER_GAME = 'REORDER_GAME';
export const SELECT_GAME = 'SELECT_GAME';
export const UPDATE_ERROR = 'UPDATE_ERROR';
export const UPDATE_GAME = 'UPDATE_GAME';
//# sourceMappingURL=actions.js.map